name: PaymentsNpm

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'auth/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cd payments
        npm install
